travis:
  secure:
    BINSTAR_TOKEN: KKM5rEtRKmtFeUqOhAVtGchxf5AiZenXLFpMUn09kvCsFT67qZV+xl75dQrGQcsSbkldqNxFtGX/WepfN6FHb2XL3WTW6c1g2PUopyu0wAIAfNuWDRNfSkmJyLKvwPAc1tgmW5mTQx7FO8IH13zksBeZmQr3UKYF5sxhhXh8u+JR08ODqVUHbgzd7ljvu++SG8bgHdy6vULCGdl1xInsSN1NpPoOKTyPIUw9uWHOt01f0vmzJkJqqNquzjkQxwicTlv/yMjs2NwBWe5vfVgVbsRvaHWpOkdYY6PTTSg826WJnhNjMOf8a+lexauTF+bsKj0ul6+wE0hnZGx5EK1iCN/YrrBGs34Jo6u3xWn46hP5SATVO3eZJwBqwZg9HyCyTd/6RcBjUu7TTbjpWkoaPjF23GcbvollE22Rnbc0OkPY+1L8rczbwZO0BxQDyJvbdifKTcW5TXwxiUUI801wHFEtXbFtpk6rcTho4TJk9N9GiAM9CVw3JbQo9Wg/qtfCJWuqPbMk537l/BtXUxYTTJjBuawMCj84cwBOkEFOGR2kMCwLCFl7j/RetvLHPUfKrT5wPYdwHfObfuKK4kQH+uVPAYpuIOLqbLyf/YHWQg5IwAO5kj+fR+3uLubFd8mLVRUH7QLWCGe2/4ZASM5p3qjpD3vWFAlO321i+mQL88E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
