travis:
  secure:
    BINSTAR_TOKEN: dnpaeP09/2Z8cLiHpDmQcSWzuOpUxnSSz1T9P0E5LfbIObQFJ6U/8w2oaEUvISCWlc2X69wv8pWzecJY29HN20R8uXtPpbwDK7XKOvCCLty4rGh8bKeECxJOiiuM+028gBMepOHSzIoLaGcCPwwPTLjhEwHKuHkIU/fYO95i4HnuA8zcjCuuJ04dVIiOEXqpkfrSvWRzJz6UZuPk/vIJl+tcbqppleRX8yahEtIE4KfcKMhcZTikxLgRhnM33SEIjmU77pEdpLSiILpXq+CIXu2/UqV+vhKVkyxMwgwdSGT/Q58gPAYlTigKlCmQ+t+ztEuKrj0bthF12j6cyWxJBXR85tsrs+sp2wbbw6NdKXGnbArED5XZlnbVsbLTISPECpFzPMvvTU6eOvDsrYAeDw0k5VuZPn3fc8QmQgT8FNTqoKaq5yz5yRF/qAbIwLuEOAGCYy8Js3+nn248A9ldIN9kCmKH+MPX/ZztTsbceV4LnND2RyJfjQ7qwkhRVw7PdudHrrZP39M8nfFCvPNCPj7AkLnJdlX6vp/A+qbtyE1wdg7+I0rS1qMyh/NhO8KUVe7Ndl+U5idTU98N0aiZYM5Hhnp0NSvd2yC/b0NIYARThmzO+AMWUkiu7KRS3dK5yZC7+RbK7J1P0qikFMCA5VBGELfXagClW6v9on/yAbc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
